POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "userName": "qmanh02",
    "password": "qmanh"

}

###

POST http://localhost:5000/api/product
Content-Type: application/json

{
    "productName": "productName",
    "productImage": "productImage",
    "productPrice": "productPrice",
    "productCategory": "productCategory"
}