export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";

export const ORDERS_DELETE_REQUEST = "ORDERS_DELETE_REQUEST";
export const ORDERS_DELETE_SUCCESS = "ORDERS_DELETE_SUCCESS";
export const ORDERS_DELETE_FAIL = "ORDERS_DELETE_FAIL";

export const ORDERS_LIST_REQUEST_ADMIN = "ORDERS_LIST_REQUEST_ADMIN";
export const ORDERS_LIST_SUCCESS_ADMIN = "ORDERS_LIST_SUCCESS_ADMIN";
export const ORDERS_LIST_FAIL_ADMIN = "ORDERS_LIST_FAIL_ADMIN";

export const ORDERS_UPDATE_REQUEST = "ORDERS_UPDATE_REQUEST";
export const ORDERS_UPDATE_SUCCESS = "ORDERS_UPDATE_SUCCESS";
export const ORDERS_UPDATE_FAIL = "ORDERS_UPDATE_FAIL";
